package com.animora.security.permission;

public enum PermissionType {

    ANIME_CREATE,
    ANIME_UPDATE,
    ANIME_DELETE,

    EPISODE_CREATE,
    EPISODE_UPDATE,
    EPISODE_DELETE,

    SEASON_CREATE,
    SEASON_UPDATE,
    SEASON_DELETE,

    GENRE_CREATE,
    GENRE_UPDATE,
    GENRE_DELETE,

    COMMENT_CREATE,
    COMMENT_DELETE_ANY,
    COMMENT_DELETE_OWN,

    FAVORITE_ADD,
    FAVORITE_DELETE_OWN,
    FAVORITE_DELETE_ANY,
}
