package com.animora.common.exception.enums;

public enum ErrorCode {

    // EPISODE
    EPISODE_ALREADY_EXISTS,
    EPISODE_NOT_IN_SEASON,
    EPISODE_NOT_FOUND,

    // ANIME
    ANIME_ALREADY_EXISTS,
    ANIME_HAS_SEASONS,
    ANIME_NOT_FOUND,

    // SEASON
    SEASON_NOT_FOUND,
    SEASON_ALREADY_EXISTS,
    SEASON_HAS_EPISODES,
    SEASON_DOES_NOT_BELONG_TO_ANIME,

    // USER
    USER_NOT_FOUND,

    //COMMENT
    COMMENT_NOT_FOUND,

    //FAVORITE
    FAVORITE_NOT_FOUND,
    FAVORITE_ALREADY_EXISTS,

    //GENRE
    GENRE_NOT_FOUND,
    GENRE_ALREADY_EXISTS,

    // AUTH - SECURITY
    UNAUTHORIZED,
    FORBIDDEN,

    // COMMON
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    NOT_FOUND,
    BAD_REQUEST

}
